[platformio]
build_dir = C:/pio_build/SmartWindow

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_filters = send_on_enter, default

lib_deps = 
    madhephaestus/ESP32Servo @ ^3.0.5
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    knolleary/PubSubClient @ ^2.8
